In [108]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, f1_score, precision_score

from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier

In [109]:
train_df = pd.read_csv("Train_data.csv")
test_df = pd.read_csv("Test_data.csv")

# Analisis Exploratorio

In [110]:
print('Number of columns:', len(train_df))
train_df.head()

Number of columns: 25192


duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0         0           tcp  ftp_data   SF        491          0     0   
1         0           udp     other   SF        146          0     0   
2         0           tcp   private   S0          0          0     0   
3         0           tcp      http   SF        232       8153     0   
4         0           tcp      http   SF        199        420     0   

   wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0               0       0    0  ...                  25   
1               0       0    0  ...                   1   
2               0       0    0  ...                  26   
3               0       0    0  ...                 255   
4               0       0    0  ...                 255   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                    0.17                    0.03   
1                    0.00                    0.60   
2                    0.10                    0.05   
3                    1.00                    0.00   
4                    1.00                    0.00   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.17                         0.00   
1                         0.88                         0.00   
2                         0.00                         0.00   
3                         0.03                         0.04   
4                         0.00                         0.00   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                  0.00                      0.00                  0.05   
1                  0.00                      0.00                  0.00   
2                  1.00                      1.00                  0.00   
3                  0.03                      0.01                  0.00   
4                  0.00                      0.00                  0.00   

   dst_host_srv_rerror_rate    class  
0                      0.00   normal  
1                      0.00   normal  
2                      0.00  anomaly  
3                      0.01   normal  
4                      0.00   normal  

[5 rows x 42 columns]

In [111]:
def checkAttack(value):
  if value == 'normal': return 0
  return 1

numeric_data = train_df.select_dtypes(include=np.number)
numeric_data["isAttack"] = train_df["class"].apply(checkAttack)
numeric_data.astype(np.number)
numeric_data.head()

duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0         0        491          0     0               0       0    0   
1         0        146          0     0               0       0    0   
2         0          0          0     0               0       0    0   
3         0        232       8153     0               0       0    0   
4         0        199        420     0               0       0    0   

   num_failed_logins  logged_in  num_compromised  ...  dst_host_srv_count  \
0                  0          0                0  ...                  25   
1                  0          0                0  ...                   1   
2                  0          0                0  ...                  26   
3                  0          1                0  ...                 255   
4                  0          1                0  ...                 255   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                    0.17                    0.03   
1                    0.00                    0.60   
2                    0.10                    0.05   
3                    1.00                    0.00   
4                    1.00                    0.00   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.17                         0.00   
1                         0.88                         0.00   
2                         0.00                         0.00   
3                         0.03                         0.04   
4                         0.00                         0.00   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                  0.00                      0.00                  0.05   
1                  0.00                      0.00                  0.00   
2                  1.00                      1.00                  0.00   
3                  0.03                      0.01                  0.00   
4                  0.00                      0.00                  0.00   

   dst_host_srv_rerror_rate  isAttack  
0                      0.00         0  
1                      0.00         0  
2                      0.00         1  
3                      0.01         0  
4                      0.00         0  

[5 rows x 39 columns]

In [112]:
numeric_data.describe()

duration     src_bytes     dst_bytes          land  wrong_fragment  \
count  25192.000000  2.519200e+04  2.519200e+04  25192.000000    25192.000000   
mean     305.054104  2.433063e+04  3.491847e+03      0.000079        0.023738   
std     2686.555640  2.410805e+06  8.883072e+04      0.008910        0.260221   
min        0.000000  0.000000e+00  0.000000e+00      0.000000        0.000000   
25%        0.000000  0.000000e+00  0.000000e+00      0.000000        0.000000   
50%        0.000000  4.400000e+01  0.000000e+00      0.000000        0.000000   
75%        0.000000  2.790000e+02  5.302500e+02      0.000000        0.000000   
max    42862.000000  3.817091e+08  5.151385e+06      1.000000        3.000000   

            urgent           hot  num_failed_logins     logged_in  \
count  25192.00000  25192.000000       25192.000000  25192.000000   
mean       0.00004      0.198039           0.001191      0.394768   
std        0.00630      2.154202           0.045418      0.488811   
min        0.00000      0.000000           0.000000      0.000000   
25%        0.00000      0.000000           0.000000      0.000000   
50%        0.00000      0.000000           0.000000      0.000000   
75%        0.00000      0.000000           0.000000      1.000000   
max        1.00000     77.000000           4.000000      1.000000   

       num_compromised  ...  dst_host_srv_count  dst_host_same_srv_rate  \
count     25192.000000  ...        25192.000000            25192.000000   
mean          0.227850  ...          115.063036                0.519791   
std          10.417352  ...          110.646850                0.448944   
min           0.000000  ...            0.000000                0.000000   
25%           0.000000  ...           10.000000                0.050000   
50%           0.000000  ...           61.000000                0.510000   
75%           0.000000  ...          255.000000                1.000000   
max         884.000000  ...          255.000000                1.000000   

       dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
count            25192.000000                 25192.000000   
mean                 0.082539                     0.147453   
std                  0.187191                     0.308367   
min                  0.000000                     0.000000   
25%                  0.000000                     0.000000   
50%                  0.030000                     0.000000   
75%                  0.070000                     0.060000   
max                  1.000000                     1.000000   

       dst_host_srv_diff_host_rate  dst_host_serror_rate  \
count                 25192.000000          25192.000000   
mean                      0.031844              0.285800   
std                       0.110575              0.445316   
min                       0.000000              0.000000   
25%                       0.000000              0.000000   
50%                       0.000000              0.000000   
75%                       0.020000              1.000000   
max                       1.000000              1.000000   

       dst_host_srv_serror_rate  dst_host_rerror_rate  \
count              25192.000000          25192.000000   
mean                   0.279846              0.117800   
std                    0.446075              0.305869   
min                    0.000000              0.000000   
25%                    0.000000              0.000000   
50%                    0.000000              0.000000   
75%                    1.000000              0.000000   
max                    1.000000              1.000000   

       dst_host_srv_rerror_rate      isAttack  
count              25192.000000  25192.000000  
mean                   0.118769      0.466140  
std                    0.317333      0.498862  
min                    0.000000      0.000000  
25%                    0.000000      0.000000  
50%                    0.000000      0.000000  
75%                    0.000000  

In [113]:
X = numeric_data.drop(['isAttack'], axis=1)
y = numeric_data['isAttack']

# Modelos

In [114]:
def generateModel(data):
  X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=0.30, random_state=42)

  model = KNeighborsClassifier()
  model = model.fit(X_train, y_train)
  y_pred = model.predict(X_test)

  result_arbol = confusion_matrix(y_test, y_pred)

  print("TP: ", result_arbol[0][0])
  print("FP: ", result_arbol[0][1])
  print("FN: ", result_arbol[1][0])
  print("TN: ", result_arbol[1][1], '\n')

  print(result_arbol)

  print ('\nAccuracy:', accuracy_score(y_test, y_pred))
  print ("Precision:", precision_score(y_test, y_pred))
  print ("Recall: ", recall_score(y_test, y_pred))
  print ("F1: ", f1_score(y_test, y_pred))

In [115]:
generateModel(X)

TP:  3988
FP:  54
FN:  59
TN:  3457 

[[3988   54]
 [  59 3457]]

Accuracy: 0.9850489547499338
Precision: 0.9846197664483053
Recall:  0.9832195676905574
F1:  0.9839191689198804


c:\Users\Brand\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:211: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [117]:
pca = PCA(n_components=12, random_state=42)
pca_X = pca.fit_transform(X)
generateModel(pca_X)

TP:  3987
FP:  55
FN:  59
TN:  3457 

[[3987   55]
 [  59 3457]]

Accuracy: 0.9849166446149775
Precision: 0.9843394077448747
Recall:  0.9832195676905574
F1:  0.9837791690381331


c:\Users\Brand\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:211: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [118]:
pca = PCA(n_components=6, random_state=42)
pca_X = pca.fit_transform(X)
generateModel(pca_X)

TP:  3990
FP:  52
FN:  58
TN:  3458 

[[3990   52]
 [  58 3458]]

Accuracy: 0.9854458851548028
Precision: 0.9851851851851852
Recall:  0.9835039817974972
F1:  0.9843438656419017


c:\Users\Brand\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:211: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [116]:
pca = PCA(n_components=2, random_state=42)
pca_X = pca.fit_transform(X)
generateModel(pca_X)

TP:  3989
FP:  53
FN:  39
TN:  3477 

[[3989   53]
 [  39 3477]]

Accuracy: 0.987827467584017
Precision: 0.984985835694051
Recall:  0.9889078498293515
F1:  0.9869429463525405


c:\Users\Brand\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:211: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
